const ES=window.NegroskyES;let customerTimeZone='America/Bogota';const $=id=>document.getElementById(id),slug=location.pathname.split('/').pop();let token=localStorage.getItem(`customer_${slug}`);if(token){document.documentElement.classList.add('customer-session');$('identify-box')?.classList.add('hidden');$('customer-home')?.classList.add('hidden')}else{$('customer-home')?.classList.add('hidden')} $('customer-name')?.removeAttribute('placeholder');$('customer-phone')?.removeAttribute('placeholder');$('customer-phone')?.setAttribute('maxlength','10');$('customer-phone')?.setAttribute('pattern','[0-9]{10}');
if(token)document.body.classList.add('customer-authenticated');
if(!token){const hidePreLoginRoulette=()=>document.getElementById('customer-roulette')?.classList.add('hidden');hidePreLoginRoulette();setInterval(hidePreLoginRoulette,500)}
let deferredInstallPrompt=null;
if('serviceWorker' in navigator)navigator.serviceWorker.register('/service-worker.js').catch(()=>{});
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstallPrompt=event;document.getElementById('install-customer-app')?.classList.remove('hidden')});
function setupCustomerInstall(){const nav=$('customer-quick-actions');if(!nav||$('install-customer-app'))return;const button=document.createElement('button');button.id='install-customer-app';button.type='button';button.className='install-action';button.textContent='📲 Instalar';button.onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;return}alert('En iPhone: pulsa Compartir y luego “Agregar a pantalla de inicio”. En Android: abre el menú del navegador y elige “Instalar aplicación”.')};nav.appendChild(button)}
function base64ToBytes(value){const pad='='.repeat((4-value.length%4)%4),raw=atob((value+pad).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function enableCustomerPush(){if(!token||!('serviceWorker' in navigator)||!('PushManager' in window)||!('Notification' in window)){showToast('Este navegador no permite notificaciones push.','error');return}try{const permission=await Notification.requestPermission();if(permission!=='granted'){showToast('Las notificaciones quedaron desactivadas. Actívalas en los ajustes del navegador.','error');return}const config=await fetch(`/api/public/${encodeURIComponent(slug)}/push-config`,{cache:'no-store'}).then(r=>r.json());if(!config.public_key)throw Error('El servidor no tiene notificaciones push configuradas.');const registration=await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription();if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64ToBytes(config.public_key)});await api('/api/public/me/push-subscription',{method:'POST',body:JSON.stringify({endpoint:subscription.endpoint,p256dh:btoa(String.fromCharCode(...new Uint8Array(subscription.getKey('p256dh')))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,''),auth:btoa(String.fromCharCode(...new Uint8Array(subscription.getKey('auth')))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')})});const button=$('enable-customer-push');if(button){button.textContent='🔔 Notificaciones activadas';button.disabled=true}showToast('Notificaciones activadas correctamente.','success')}catch(e){showToast(e.message||'No se pudo activar las notificaciones.','error')}}
function setupCustomerPush(){if(!customerModuleEnabled('notifications')||!('Notification' in window))return;const profile=$('customer-profile');if(!profile||$('enable-customer-push'))return;const button=document.createElement('button');button.id='enable-customer-push';button.type='button';button.className='secondary full';button.textContent=Notification.permission==='granted'?'🔔 Activar notificaciones':'🔔 Recibir notificaciones';button.onclick=enableCustomerPush;profile.appendChild(button)}
const quickHome=$('customer-home');if(quickHome&&!$('customer-quick-actions')){quickHome.insertAdjacentHTML('afterbegin','<nav id="customer-quick-actions" class="customer-quick-actions" aria-label="Accesos rápidos"><button type="button" data-scroll-target="cards" data-customer-module="loyalty">⭐ Fidelización</button><button type="button" data-scroll-target="rewards" data-customer-module="loyalty">🎁 Premios</button><button type="button" data-scroll-target="customer-schedule">🕒 Horarios</button><button id="quick-appointment" type="button" data-scroll-target="appointment-box" data-customer-module="appointments">📅 Reservar</button><button type="button" data-scroll-target="customer-profile">👤 Perfil</button><a class="quick-directory-link" href="/cliente">🏪 Más negocios</a><button id="install-customer-app" type="button" class="install-action">📲 Instalar</button></nav>');quickHome.querySelectorAll('[data-scroll-target]').forEach(button=>button.onclick=()=>{const target=$(button.dataset.scrollTarget);if(target?.id==='customer-schedule'){target.querySelector('#customer-schedule-content')?.classList.remove('hidden');target.querySelector('#customer-schedule-toggle')?.setAttribute('aria-expanded','true')}target?.scrollIntoView({behavior:'smooth',block:'start'})});$('install-customer-app').onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;return}alert('En iPhone: pulsa Compartir y luego “Agregar a pantalla de inicio”. En Android: abre el menú del navegador y elige “Instalar aplicación”.')}
}
// Until the server confirms the business permissions, optional modules stay hidden.
// This prevents stale HTML/cache data from briefly exposing a disabled feature.
const CUSTOMER_MODULE_DEFAULTS={loyalty:false,appointments:false,time_sales:false,notifications:false,public_page:false,raffles:false,roulette:false};let customerModules={...CUSTOMER_MODULE_DEFAULTS};let publicPageDisabled=false;
function normalizeCustomerModules(modules){if(Array.isArray(modules)){const allowed=new Set(modules);return Object.fromEntries(Object.keys(CUSTOMER_MODULE_DEFAULTS).map(key=>[key,allowed.has(key)]))}return {...CUSTOMER_MODULE_DEFAULTS,...Object.fromEntries(Object.entries(modules||{}).map(([key,value])=>[key,Boolean(value)]))}}
function customerModuleEnabled(key){return key==='raffles'||key==='roulette'||customerModules[key]!==false}
function setAppointmentVisibility(visible){const allowed=Boolean(visible)&&customerModuleEnabled('appointments');$('appointment-box')?.classList.toggle('hidden',!allowed);$('quick-appointment')?.classList.toggle('hidden',!allowed)}
function applyCustomerModuleVisibility(modules={}){customerModules=normalizeCustomerModules(modules);const loyaltyOn=customerModuleEnabled('loyalty'),appointmentsOn=customerModuleEnabled('appointments'),rouletteOn=customerModuleEnabled('roulette');$('cards')?.classList.toggle('hidden',!loyaltyOn);if(!loyaltyOn)$('rewards')?.classList.add('hidden');if(!appointmentsOn)setAppointmentVisibility(false);$('customer-roulette')?.classList.toggle('hidden',!rouletteOn);if(!rouletteOn&&$('customer-roulette-list'))$('customer-roulette-list').replaceChildren();document.querySelectorAll('[data-customer-module]').forEach(el=>el.classList.toggle('hidden',!customerModuleEnabled(el.dataset.customerModule)));document.body.dataset.enabledModules=Object.entries(customerModules).filter(([,enabled])=>enabled).map(([key])=>key).join(',')}
function showPublicPageDisabled(){const main=document.querySelector('main.mobile-shell');if(!main)return;let panel=$('public-disabled');if(!panel){panel=document.createElement('section');panel.id='public-disabled';panel.className='hero-card';main.appendChild(panel)}Array.from(main.children).forEach(el=>{if(el===panel)return;if(!el.classList.contains('hidden')){el.dataset.hiddenByPublic='true';el.classList.add('hidden')}});panel.innerHTML='<p class="eyebrow">PÁGINA NO DISPONIBLE</p><h2>Este negocio no está disponible</h2><p class="muted">El Administrador General desactivó la página pública de este negocio.</p>';panel.classList.remove('hidden');publicPageDisabled=true}
function hidePublicPageDisabled(){if(!publicPageDisabled)return;const main=document.querySelector('main.mobile-shell');main?.querySelectorAll('[data-hidden-by-public]').forEach(el=>{el.classList.remove('hidden');delete el.dataset.hiddenByPublic});$('public-disabled')?.classList.add('hidden');publicPageDisabled=false}
setAppointmentVisibility(false);
const successAudio=new Audio('/static/success.wav?v=15');successAudio.preload='auto';successAudio.setAttribute('playsinline','');successAudio.playsInline=true;let soundUnlocked=false;function armSound(){if(soundUnlocked)return;try{successAudio.load();successAudio.volume=.01;successAudio.currentTime=0;const play=successAudio.play();if(play)play.then(()=>{setTimeout(()=>{successAudio.pause();successAudio.currentTime=0;successAudio.volume=1;soundUnlocked=true},120)}).catch(()=>{})}catch(e){}}function successSound(){try{successAudio.volume=1;successAudio.currentTime=0;const play=successAudio.play();if(play)play.catch(()=>{const fallback=new Audio('/static/success.wav?v=15');fallback.setAttribute('playsinline','');fallback.playsInline=true;fallback.volume=1;fallback.play().catch(()=>{})})}catch(e){}}document.addEventListener('touchstart',armSound,{once:true,passive:true});document.addEventListener('pointerdown',armSound,{once:true,passive:true});
async function api(path,o={}){const h={'Content-Type':'application/json'};if(token)h.Authorization=`Bearer ${token}`;const r=await fetch(path,{...o,cache:'no-store',headers:h});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(Array.isArray(b.detail)?'Revisa los datos e inténtalo de nuevo.':b.detail||'No fue posible completar la operación');return b}
$('business-title').textContent=slug.replaceAll('-',' ').toUpperCase();
let publicBrandingFingerprint='',publicBranding=null;
const publicDayNames=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];
function formatBusinessHour(value){if(!value)return'';const [hour,minute]=value.split(':').map(Number);return new Intl.DateTimeFormat('es-CO',{hour:'numeric',minute:'2-digit',hour12:true,timeZone:'UTC'}).format(new Date(Date.UTC(2020,0,1,hour,minute)))}
function safePublicLink(value){return /^https?:\/\//i.test(value||'')?value:null}
function socialMark(kind){const p={phone:'<path d="M6 3l3 5-2 1c1 3 3 5 6 6l1-2 5 3-1 4C10 19 5 14 4 6l2-3Z"/>',whatsapp:'<path d="M12 2a9 9 0 0 0-7.7 13.7L3 21l5.5-1.3A9 9 0 1 0 12 2Zm4.5 12.3c-.3.8-1.4 1.4-2.1 1.5-1.2.1-5.2-2-6.4-4.1-.7-1.2-.3-2.4.5-3.1l1 2-1 .7c.9 1.7 2.2 3 4 3.8l.7-1 2 .2Z"/>',instagram:'<path d="M7 2h10a5 5 0 0 1 5 5v10a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5V7a5 5 0 0 1 5-5Zm5 6a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm5-2a1 1 0 1 0 0 2 1 1 0 0 0 0-2Zm-5 4a2 2 0 1 1 0 4 2 2 0 0 1 0-4Z"/>',facebook:'<path d="M14 22v-8h3l.5-3H14V9.5c0-1 .4-1.5 1.7-1.5H18V5c-.4-.1-1.4-.2-2.5-.2-2.5 0-4.2 1.5-4.2 4.3V11H8v3h3.3v8H14Z"/>',tiktok:'<path d="M14 2h3c.4 2.2 1.7 3.6 4 4v3a8 8 0 0 1-4-1.3v7.4A6 6 0 1 1 11 9v3a3 3 0 1 0 3 3V2Z"/>',website:'<path d="M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Zm0 2c1.2 1.5 2 3.2 2.3 5H9.7c.3-1.8 1.1-3.5 2.3-5ZM4.3 10h3.4a16 16 0 0 0 0 4H4.3a8 8 0 0 1 0-4Zm.9 6h3.2c.4 1.5 1.1 2.9 2 4A8 8 0 0 1 5.2 16Zm4.5-2a14 14 0 0 1 0-4h4.6a14 14 0 0 1 0 4H9.7Zm4.6 6c.9-1.1 1.6-2.5 2-4h3.2a8 8 0 0 1-5.2 4Zm2-6a16 16 0 0 0 0-4h3.4a8 8 0 0 1 0 4h-3.4Z"/>',maps:'<path d="M12 2a7 7 0 0 0-7 7c0 5 7 13 7 13s7-8 7-13a7 7 0 0 0-7-7Zm0 10a3 3 0 1 1 0-6 3 3 0 0 1 0 6Z"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true">${p[kind]||p.website}</svg>`}
function applyCustomerModuleOrder(b){
  const home=$('customer-home'),map={contact:$('public-business-info'),profile:$('customer-profile'),campaigns:$('cards'),rewards:$('rewards'),appointments:$('appointment-box')};
  const device=(window.matchMedia&&window.matchMedia('(max-width:899px)').matches)?'mobile':'desktop';
  const defaults=device==='mobile'?{contact:100,profile:100,campaigns:100,rewards:100,appointments:100}:{contact:100,profile:50,campaigns:50,rewards:50,appointments:50};
  const widths={...defaults},positions={contact:1,profile:1,campaigns:1,rewards:1,appointments:1},saved=b['module_widths_'+device];
  if(saved&&typeof saved==='object'){
    for(const [key,value] of Object.entries(saved))if(key in widths&&Number(value))widths[key]=Number(value);
  }else for(const row of String(saved||'').split(',')){
    const [key,value,start]=row.split(':');
    if(key in widths&&Number(value)){widths[key]=Number(value);if(Number(start))positions[key]=Number(start)}
  }
  for(const [key,el] of Object.entries(map))if(el){
    const span=Math.max(3,Math.min(12,Math.round(widths[key]/100*12)));
    const start=Math.max(1,Math.min(13-span,positions[key]||1));
    el.dataset.publicModule=key;
    el.classList.toggle('module-compact',widths[key]<=50);
    el.style.setProperty('--module-span',span);
    el.style.setProperty('--module-start',start);
    el.style.setProperty('--module-order',String(String(b['module_order_'+device]||'').split(',').indexOf(key)+1));
  }
  for(const key of String(b['module_order_'+device]||'').split(','))if(map[key])home.appendChild(map[key]);
}
function renderPublicBusinessInfo(b){
  const section=$('public-business-info'),buttons=$('public-contact-buttons');buttons.replaceChildren();
  const links=[['phone','Llamar',b.contact_phone?`tel:${b.contact_phone.replace(/[^+\d]/g,'')}`:null],['whatsapp','WhatsApp',b.whatsapp_number?`https://wa.me/${b.whatsapp_number.replace(/\D/g,'')}`:null],['instagram','Instagram',safePublicLink(b.instagram_url)],['facebook','Facebook',safePublicLink(b.facebook_url)],['tiktok','TikTok',safePublicLink(b.tiktok_url)],['website','Sitio web',safePublicLink(b.website_url)],['maps','Cómo llegar',safePublicLink(b.maps_url)]];
  if(b.show_contact)for(const [kind,label,url] of links){if(!url)continue;const a=document.createElement('a');a.className='social-button';a.dataset.network=kind;a.href=url;a.target='_blank';a.rel='noopener noreferrer';const icon=document.createElement('span');icon.className='social-logo';icon.innerHTML=socialMark(kind);const text=document.createElement('span');text.className='social-label';text.textContent=label;a.append(icon,text);buttons.appendChild(a)}
  const address=$('public-address');address.textContent=b.address?`📍 ${b.address}`:'';address.classList.toggle('hidden',!b.show_contact||!b.address);
  const hours=$('public-hours');hours.replaceChildren();if(b.show_business_hours){const title=document.createElement('b');title.textContent='🕒 Horario de atención';hours.appendChild(title);for(const row of b.business_hours||[]){const line=document.createElement('span');line.textContent=`${publicDayNames[row.weekday]}: ${row.enabled?formatBusinessHour(row.opens_at)+' – '+formatBusinessHour(row.closes_at):'Cerrado'}`;hours.appendChild(line)}}hours.classList.toggle('hidden',!b.show_business_hours);
  const visible=(b.show_contact&&(buttons.children.length||b.address))||b.show_business_hours;section.classList.toggle('hidden',!visible)
}
function renderCustomerSchedule(b){const home=$('customer-home');if(!home)return;let box=$('customer-schedule');if(!box){box=document.createElement('section');box.id='customer-schedule';box.className='hero-card hidden';box.innerHTML='<button id="customer-schedule-toggle" type="button" class="schedule-toggle" aria-expanded="false">🕒 Horarios <span>＋</span></button><div id="customer-schedule-content" class="schedule-content hidden"></div>';home.prepend(box);$('customer-schedule-toggle').onclick=()=>{const content=$('customer-schedule-content'),open=content.classList.toggle('hidden');$('customer-schedule-toggle').setAttribute('aria-expanded',String(!open));$('customer-schedule-toggle').querySelector('span').textContent=open?'＋':'−'}}const rows=b.business_hours||[];const enabled=Boolean(b.show_business_hours&&rows.length);box.classList.toggle('hidden',!enabled);if(!enabled)return;const content=$('customer-schedule-content');content.innerHTML='<h3>Horario de atención</h3>'+rows.map(row=>`<div class="customer-hour-row"><span>${publicDayNames[row.weekday]}</span><b>${row.enabled?formatBusinessHour(row.opens_at)+' – '+formatBusinessHour(row.closes_at):'Cerrado'}</b></div>`).join('');}
function renderCustomerSchedule(b){const home=$('customer-home');if(!home)return;let box=$('customer-schedule'),wasOpen=box&&!box.classList.contains('hidden');if(!box){box=document.createElement('section');box.id='customer-schedule';box.className='schedule-panel hidden';box.innerHTML='<div id="customer-schedule-content" class="schedule-content"></div>';home.insertBefore(box,$('customer-profile'))}const rows=b.business_hours||[],enabled=Boolean(b.show_business_hours&&rows.length);box.classList.toggle('hidden',!enabled||!wasOpen);if(!enabled)return;const content=$('customer-schedule-content');content.innerHTML='<h3>Horario de atención</h3>'+rows.map(row=>`<div class="customer-hour-row"><span>${publicDayNames[row.weekday]}</span><b>${row.enabled?formatBusinessHour(row.opens_at)+' – '+formatBusinessHour(row.closes_at):'Cerrado'}</b></div>`).join('')}
function syncQuickLocationButton(b){const nav=$('customer-quick-actions');if(!nav)return;let link=$('quick-location');if(!b.maps_url){link?.remove();return}if(!link){link=document.createElement('a');link.id='quick-location';link.className='quick-directory-link';link.textContent='📍 Ubicación';link.target='_blank';link.rel='noopener noreferrer';nav.insertBefore(link,$('install-customer-app')||null)}link.href=safePublicLink(b.maps_url)||b.maps_url}
function bindScheduleQuickButton(){const button=document.querySelector('[data-scroll-target="customer-schedule"]');if(!button)return;button.onclick=()=>{const box=$('customer-schedule'),open=box?.classList.toggle('hidden');if(!open)box?.scrollIntoView({behavior:'smooth',block:'start'})}}
function applyPublicBranding(b){
  renderCustomerSchedule(b);bindScheduleQuickButton();syncQuickLocationButton(b);
  publicBranding=b;applyCustomerModuleVisibility(b.enabled_modules||b.modules||{});
  document.documentElement.style.setProperty('--purple',b.primary_color);
  document.documentElement.style.setProperty('--purple2',b.secondary_color);
  document.documentElement.style.setProperty('--brand-button',b.button_color);
  const background=b.background_style==='light'?'#f5f3ff':b.background_style==='dark'?'#07070d':b.background_color;
  document.documentElement.style.setProperty('--bg',background);
  document.documentElement.style.setProperty('--brand-text',b.text_color);
  document.documentElement.style.setProperty('--brand-font-scale',b.font_scale/100);
  document.documentElement.style.setProperty('--brand-card-opacity',b.card_opacity+'%');
  document.documentElement.style.setProperty('--brand-stamp-done',b.stamp_done_color);
  document.documentElement.style.setProperty('--brand-stamp-pending',b.stamp_pending_color);
  document.documentElement.style.setProperty('--brand-progress-start',b.progress_start_color);
  document.documentElement.style.setProperty('--brand-progress-end',b.progress_end_color);
  document.documentElement.style.setProperty('--brand-bg-image',b.background_url?`url(${b.background_url}?v=${encodeURIComponent(b.updated_at||Date.now())})`:'none');
  document.documentElement.style.setProperty('--brand-bg-fit-desktop',b.background_fit_desktop||'cover');
  document.documentElement.style.setProperty('--brand-bg-x-desktop',(b.background_x_desktop??50)+'%');
  document.documentElement.style.setProperty('--brand-bg-y-desktop',(b.background_y_desktop??50)+'%');
  document.documentElement.style.setProperty('--brand-bg-fit-mobile',b.background_same_frame?(b.background_fit_desktop||'cover'):(b.background_fit_mobile||'cover'));
  document.documentElement.style.setProperty('--brand-bg-x-mobile',(b.background_same_frame?(b.background_x_desktop??50):(b.background_x_mobile??50))+'%');
  document.documentElement.style.setProperty('--brand-bg-y-mobile',(b.background_same_frame?(b.background_y_desktop??50):(b.background_y_mobile??50))+'%');
  document.documentElement.style.setProperty('--brand-bg-image-opacity',(b.background_image_opacity??100)/100);
  document.documentElement.style.setProperty('--brand-bg-overlay-opacity',(b.background_overlay_opacity??35)/100);
  document.documentElement.style.setProperty('--brand-logo-size',(b.logo_size??64)+'px');
  document.documentElement.style.setProperty('--brand-logo-opacity',(b.logo_opacity??100)/100);
  document.documentElement.style.setProperty('--brand-logo-background',b.logo_background_color||'#ffffff');
  document.body.classList.add('brand-customer');document.documentElement.classList.add('customer-ready');document.body.classList.toggle('social-floating',b.social_layout==='floating');document.body.dataset.socialDisplay=b.social_display_mode||'both';document.body.dataset.socialSize=b.social_size||'medium';document.body.dataset.socialPosition=b.social_position||'bottom-right';document.body.classList.toggle('social-hide-mobile',b.show_social_mobile===false);document.body.classList.toggle('social-hide-desktop',b.show_social_desktop===false);
  document.body.classList.toggle('brand-light',b.background_style==='light');
  document.body.classList.remove('brand-card-soft','brand-card-solid','brand-card-glass');
  document.body.classList.add(`brand-card-${b.card_style}`);
  document.body.dataset.cardShape=b.card_shape;document.body.dataset.buttonShape=b.button_shape;document.body.dataset.stampShape=b.stamp_shape;document.body.dataset.progressStyle=b.progress_style;document.body.dataset.font=b.font_family;document.body.dataset.logoShape=b.logo_shape;document.body.dataset.logoFit=b.logo_fit;
  document.body.classList.toggle('brand-hide-profile',!b.show_profile);document.body.classList.toggle('brand-hide-rewards',!b.show_rewards);document.body.classList.toggle('brand-hide-appointments',!b.show_appointments);
  $('business-title').textContent=b.display_name;
  $('business-welcome').textContent=b.welcome_text;
  const logo=$('business-logo');
  if(b.logo_url){const img=document.createElement('img');img.src=`${b.logo_url}?v=${encodeURIComponent(b.updated_at||Date.now())}`;img.alt=`Logo de ${b.display_name}`;logo.textContent='';logo.appendChild(img)}
  else {logo.textContent=(b.display_name||'N').trim().charAt(0).toUpperCase()||'N'}
  renderPublicBusinessInfo(b);applyCustomerModuleOrder(b);
  document.title=`${b.display_name} · Mi tarjeta`;
}
async function loadPublicBranding(){try{
  const r=await fetch(`/api/public/${slug}/branding?refresh=${Date.now()}`,{cache:'no-store'});
  if(!r.ok)throw Error(`branding_${r.status}`);
  hidePublicPageDisabled();
  const b=await r.json(),wasLoaded=!!publicBrandingFingerprint;
  const fingerprint=JSON.stringify(b);
  if(fingerprint!==publicBrandingFingerprint){publicBrandingFingerprint=fingerprint;applyPublicBranding(b);if(wasLoaded&&token)showHome().catch(()=>{})}
}catch(e){if(e.message==='branding_404'){showPublicPageDisabled();return}console.warn('No se pudo cargar la personalización del negocio',e)}}
async function loadPublicBranches(){try{const rows=await fetch(`/api/public/${slug}/branches`).then(r=>r.ok?r.json():[]);if(!rows.length)return;const label=document.createElement('label');label.innerHTML=`Sucursal que visitas<select id="customer-branch"><option value="">Selecciona una sucursal</option>${rows.map(b=>`<option value="${b.id}">${b.name}${b.city?' · '+b.city:''}</option>`).join('')}</select>`;$('customer-phone').closest('label').after(label)}catch(e){}}
async function identifyFromDirectory(){try{const saved=JSON.parse(localStorage.getItem('negrosky_global_customer')||'null');if(!saved?.name||!saved?.phone)return false;const r=await api(`/api/public/${slug}/identify`,{method:'POST',body:JSON.stringify({name:saved.name,phone:saved.phone,marketing_consent:false,branch_id:null})});token=r.access_token;localStorage.setItem(`customer_${slug}`,token);document.documentElement.classList.add('customer-session');$('identify-box')?.classList.add('hidden');return true}catch(e){return false}}
function openWhatsAppOptIn(name,phone,blankWindow){const number=String(publicBranding?.whatsapp_number||'').replace(/\D/g,'');if(!number)return false;const message=`Hola, quiero recibir promociones e información por WhatsApp. Mi nombre es ${String(name||'').trim()}.`;const url=`https://wa.me/${number}?text=${encodeURIComponent(message)}`;if(blankWindow)blankWindow.location.href=url;else window.open(url,'_blank','noopener');localStorage.setItem(`negrosky_whatsapp_optin_${slug}_${String(phone).replace(/\D/g,'')}`,'1');return true}
$('identify-form').onsubmit=async e=>{e.preventDefault();const wantsWhatsApp=$('consent').checked;const name=$('customer-name').value.trim(),phone=$('customer-phone').value.replace(/\D/g,'');let whatsappWindow=null;if(wantsWhatsApp&&publicBranding?.whatsapp_number)whatsappWindow=window.open('about:blank','_blank');try{const r=await api(`/api/public/${slug}/identify`,{method:'POST',body:JSON.stringify({name,phone,marketing_consent:wantsWhatsApp,branch_id:+($('customer-branch')?.value||0)||null})});token=r.access_token;localStorage.setItem(`customer_${slug}`,token);localStorage.setItem('negrosky_global_customer',JSON.stringify({name,phone}));document.documentElement.classList.add('customer-session');$('identify-box')?.classList.add('hidden');$('customer-home')?.classList.add('hidden');await loadPublicBranding();if(wantsWhatsApp&&!openWhatsAppOptIn(name,phone,whatsappWindow)&&whatsappWindow)whatsappWindow.close();await showHome()}catch(x){if(whatsappWindow)whatsappWindow.close();$('customer-error').textContent=x.message;showToast(x.message,'error')}};
function rewardAvailability(c){if(c.reward_stock!==null&&c.rewards_remaining===0)return'<div class="exhausted-card"><div>⛔</div><h3>Premios agotados</h3><p>Agradecemos tu interés. Esta campaña ha entregado todos los premios disponibles.</p></div>';if(c.reward_display==='unlimited')return'<p class="reward-availability">🎁 Premios ilimitados</p>';if(c.reward_display==='quantity')return`<p class="reward-availability">🎁 Quedan <b>${c.rewards_remaining}</b> de ${c.reward_stock} premios</p>`;return''}
function rewardGroups(rewards){const groups={};rewards.filter(r=>r.status==='available').forEach(r=>{const k=`${r.program_id}_${r.name}`;(groups[k]??={...r,count:0}).count++});return Object.values(groups)}
function syncAutomaticModules({hasRewards=false,hasAppointments}={}){
  // La disponibilidad real manda: el cliente no ve módulos vacíos.
  $('cards')?.classList.toggle('hidden',!customerModuleEnabled('loyalty'));
  $('rewards')?.classList.toggle('hidden',!customerModuleEnabled('loyalty')||!hasRewards);
  if(typeof hasAppointments==='boolean')setAppointmentVisibility(customerModuleEnabled('appointments')&&hasAppointments);
  else if(!customerModuleEnabled('appointments'))setAppointmentVisibility(false);
}
const loyaltyCardMarkup = c => window.NegroskyCard.render({...c,button_label:publicBranding?.button_label});
async function showHome(){try{const d=await api('/api/public/me/cards');localStorage.setItem('negrosky_global_customer',JSON.stringify({name:d.customer.name,phone:d.customer.phone}));if(d.enabled_modules)applyCustomerModuleVisibility(d.enabled_modules);$('identify-box').classList.add('hidden');$('customer-home').classList.remove('hidden');$('hello').textContent=`¡Hola, ${d.customer.name}!`;setupCustomerInstall();setupCustomerPush();$('cards').innerHTML=d.cards.length?d.cards.map(loyaltyCardMarkup).join(''):'<div class="hero-card"><p>Aún no hay tarjetas activas.</p></div>';const groups=rewardGroups(d.rewards);$('rewards').innerHTML=groups.map(g=>`<div class="loyalty-card"><p class="eyebrow">PREMIOS DISPONIBLES · ${g.program_name}</p><h2>${g.name}</h2><p>Tienes <b>${g.count}</b> premio${g.count===1?'':'s'} para reclamar.</p><label>¿Cuántos deseas reclamar?<select id="reward-qty-${g.program_id}">${Array.from({length:g.count},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join('')}</select></label><button class="full" onclick="rewardBatch(${g.program_id},+document.getElementById('reward-qty-${g.program_id}').value)">Reclamar premio${g.count===1?'':'s'}</button></div>`).join('');syncAutomaticModules({hasRewards:groups.length});}catch(e){localStorage.removeItem(`customer_${slug}`);token=null}}
let baseHomePromise=null;const renderHomeWithSession=showHome;showHome=async function(){if(baseHomePromise)return baseHomePromise;baseHomePromise=(async()=>{await renderHomeWithSession();if(!token){document.documentElement.classList.remove('customer-session');document.documentElement.classList.remove('customer-ready');$('identify-box')?.classList.remove('hidden');$('customer-home')?.classList.add('hidden')}})();try{return await baseHomePromise}finally{baseHomePromise=null}}
function formatDate(value){if(!value)return'';const normalized=value.includes('T')?value:value.replace(' ','T')+'Z';return new Intl.DateTimeFormat('es-CO',{dateStyle:'medium',timeStyle:'short',hour12:true}).format(new Date(normalized))}
async function loadHistory(){const h=await api('/api/public/me/history');$('history-summary').innerHTML=`<div class="history-stat"><b>${h.summary.purchases}</b><span>Compras</span></div><div class="history-stat"><b>${h.summary.rewards_earned}</b><span>Premios ganados</span></div><div class="history-stat"><b>${h.summary.rewards_claimed}</b><span>Premios reclamados</span></div>`;const events=[...h.purchases.map(p=>({type:'purchase',date:p.created_at,title:'Compra validada',detail:`${p.program_name} · ${p.branch_name}`})),...h.rewards.map(r=>({type:'reward',date:r.claimed_at||r.unlocked_at,title:r.status==='used'?'Premio reclamado':'Premio ganado',detail:`${r.name}${r.branch_name?' · '+r.branch_name:''}`}))].sort((a,b)=>new Date(b.date)-new Date(a.date));$('history-list').innerHTML=events.length?events.map(e=>`<div class="history-item ${e.type==='reward'?'reward':''}"><p><b>${e.title}</b></p><p>${e.detail}</p><p class="history-date">${formatDate(e.date)}</p></div>`).join(''):'<p class="muted">Todavía no hay movimientos.</p>'}
async function displayQr(result,renew){
  $('customer-home').classList.add('hidden');$('qr-modal').classList.remove('hidden');
  const showCode=next=>{result=next;const direct=result.worker_url||`${location.origin}/worker?code=${result.code}`;$('qr-image').classList.remove('hidden');$('qr-code').classList.remove('hidden');$('countdown').parentElement.classList.remove('hidden');$('qr-image').style.opacity=1;$('qr-code').style.opacity=1;$('qr-image').src=`/api/qr/${result.code}.png?t=${Date.now()}`;$('qr-code').textContent=result.code.replace(/^(\d{3})(\d{3})$/,'$1 $2');$('qr-link').href=direct;$('qr-link').textContent=direct};
  showCode(result);
  const status=$('customer-operation-status');status.className='status-panel pending';status.textContent='Esperando validación del trabajador…';
  let n=result.expires_in_seconds||60,renewing=false;$('countdown').textContent=n;
  const refreshCode=async()=>{if(renewing)return;renewing=true;status.className='status-panel pending';status.textContent='Renovando QR y código automáticamente…';try{const next=await renew();showCode(next);n=next.expires_in_seconds||60;$('countdown').textContent=n;status.textContent='Código renovado. Esperando validación del trabajador…';showToast('Nuevo QR y código disponibles.')}catch(e){status.className='status-panel error';status.textContent='No se pudo renovar. Reintentando automáticamente…'}finally{renewing=false}};
  const countdown=setInterval(()=>{n=Math.max(0,n-1);$('countdown').textContent=n;if(n===0)refreshCode()},1000);
  const polling=setInterval(async()=>{const checkedCode=result.code;try{const check=await api(`/api/public/me/operation-status/${checkedCode}`);if(check.status==='validated'){clearInterval(polling);clearInterval(countdown);const completed=result.operation==='purchase'&&check.mission_completed;showToast(completed?'¡Misión completada! Ya puedes reclamar tu premio.':'Operación validada correctamente.','success');$('operation-title').textContent=completed?'¡Misión completada!':result.operation==='purchase'?'¡Compra validada!':'¡Premio entregado!';status.className=completed?'mission-complete':'validation-success';status.innerHTML=completed?`<div class="confetti">🎉 ✨ 🎊 ⭐ 🎉</div><div class="trophy">🏆</div><h2>¡Misión completada!</h2><p>Ganaste: <b>${check.reward_name}</b></p><button class="claim-button" onclick="location.reload()">Ver y reclamar mi premio</button>`:`<div class="success-check">✓</div><h2>¡Validación exitosa!</h2><p>${result.operation==='purchase'?`Nuevo progreso: ${check.progress}/${check.target}`:'Premio entregado correctamente'}</p>`;$('qr-image').classList.add('hidden');$('qr-code').classList.add('hidden');$('countdown').parentElement.classList.add('hidden');successSound();if(navigator.vibrate)navigator.vibrate([180,70,180])}else if(check.status==='expired'&&checkedCode===result.code){refreshCode()}}catch(e){status.className='status-panel error';status.textContent='No se pudo consultar la validación.'}},1200);
}
function operationError(message){showToast(message,'error');const banner=$('service-banner');banner.classList.remove('hidden');banner.innerHTML=`<div class="service-icon">⚠️</div><h2>No fue posible generar el código</h2><p>${message}</p><small>Tu progreso no fue modificado.</small>`;banner.scrollIntoView({behavior:'smooth',block:'center'})}
async function purchase(id){armSound();const renew=()=>api('/api/public/me/purchase-token',{method:'POST',body:JSON.stringify({program_id:id})});try{await displayQr(await renew(),renew)}catch(e){operationError(e.message)}}
async function rewardBatch(programId,quantity){armSound();const renew=()=>api('/api/public/me/rewards/batch-token',{method:'POST',body:JSON.stringify({program_id:programId,quantity})});try{await displayQr(await renew(),renew)}catch(e){operationError(e.message)}}
// Mantiene abierta la vista del cliente sincronizada cuando el negocio guarda cambios desde el panel.
setTimeout(loadPublicBranding,5000);
loadPublicBranding().then(async()=>{if(!token)await identifyFromDirectory();if(token)return showHome()}).catch(()=>{if(token){localStorage.removeItem(`customer_${slug}`);token=null;document.documentElement.classList.remove('customer-session');document.documentElement.classList.remove('customer-ready');$('identify-box')?.classList.remove('hidden');$('customer-home')?.classList.add('hidden')}});

let serviceOpen=true;
function renderCustomerServiceState(open,message){const content=$('customer-schedule-content');if(!content)return;let state=$('customer-service-state');if(!state){state=document.createElement('div');state.id='customer-service-state';content.prepend(state)}state.className=open?'service-state open':'service-state closed';state.innerHTML=open?'🟢 <b>En servicio</b>':`🔴 <b>Fuera de servicio</b><p>${ES.escape(message||'En este momento el negocio está cerrado.')}</p>`}
async function syncCustomerScheduleStatus(){if(!token)return;try{const profile=await api('/api/public/me/cards'),branch=profile.customer.origin_branch_id,state=await fetch(`/api/public/${slug}/service-status${branch?'?branch_id='+branch:''}`,{cache:'no-store'}).then(r=>r.json());renderCustomerServiceState(!!state.open,state.message)}catch(e){}}
async function checkServiceStatus(){if(!token)return;try{const profile=await api('/api/public/me/cards');const branch=profile.customer.origin_branch_id;const state=await fetch(`/api/public/${slug}/service-status${branch?'?branch_id='+branch:''}`).then(r=>r.json());serviceOpen=!!state.open;const banner=$('service-banner');if(state.open){banner.classList.add('hidden')}else{banner.classList.remove('hidden');banner.innerHTML=`<div class="service-icon">🌙</div><h2>Fuera de servicio</h2><p>${state.message}</p><small>Tu progreso y tus premios permanecen guardados.</small>`}document.querySelectorAll('.loyalty-card button').forEach(button=>{if(!button.textContent.includes('agotados'))button.disabled=!state.open})}catch(e){}}
async function showCampaignNotice(){if(!token||!customerModuleEnabled('loyalty'))return;try{const profile=await api('/api/public/me/cards');if(!profile.cards.length){$('cards').innerHTML='<div class="no-campaigns"><div>✨</div><h2>Próximamente nuevas campañas</h2><p>En este momento no hay campañas de fidelización disponibles. Cuando el negocio active una, aparecerá aquí automáticamente.</p><small>Tu cuenta y tu información permanecen registradas.</small></div>'}}catch(e){}}
async function loadCustomerCollaborations(){try{const response=await fetch(`/api/public/${encodeURIComponent(customerPathSlug)}/collaborations`,{cache:'no-store'});if(!response.ok)return;const rows=await response.json();const item=rows.find(x=>!sessionStorage.getItem(`negrosky_collaboration_${customerPathSlug}_${x.id}`));if(!item)return;sessionStorage.setItem(`negrosky_collaboration_${customerPathSlug}_${item.id}`,'1');const seconds=Math.max(1,Math.min(60,Number(item.ad_seconds)||5));const overlay=document.createElement('div');overlay.className='collaboration-overlay';overlay.innerHTML=`<article class="collaboration-ad"> <button type="button" class="collaboration-close" aria-label="Cerrar">×</button><p class="eyebrow">COLABORACIÓN · ${ES.escape(item.partner_name||'Negocio aliado')}</p><h2>${ES.escape(item.title)}</h2>${item.image_url?`<img src="${ES.escape(item.image_url)}" alt="Publicidad de colaboración">`:''}<p>${ES.escape(item.message||'Conoce esta promoción especial.')}</p><small>Esta publicidad se cerrará en ${seconds} segundos.</small></article>`;document.body.appendChild(overlay);const close=()=>overlay.remove();overlay.querySelector('.collaboration-close').onclick=close;setTimeout(close,seconds*1000)}catch(e){}}
setTimeout(loadCustomerCollaborations,900);
const originalShowHome=showHome;let sessionHomePromise=null;showHome=async function(){if(sessionHomePromise)return sessionHomePromise;sessionHomePromise=(async()=>{await originalShowHome();if(!token)return;await Promise.all([checkServiceStatus(),syncCustomerScheduleStatus(),showCampaignNotice(),loadAppointmentModule(),loadCustomerRaffles(),loadCustomerCollaborations()])})();try{return await sessionHomePromise}finally{sessionHomePromise=null}};
setTimeout(checkServiceStatus,300);
setTimeout(showCampaignNotice,350);

async function loadCustomerAppointmentServices(){
  const branchId=+$('customer-appointment-branch').value;
  if(!branchId)return;
  try{const services=await api(`/api/public/${slug}/appointment-services?branch_id=${branchId}`);if(!services.length){setAppointmentVisibility(false);$('customer-calendar-days').textContent='No hay citas disponibles para esta sucursal.';$('customer-appointment-service').innerHTML='<option value="">Sin servicios configurados</option>';$('appointment-availability').textContent='Todavía no hay servicios de citas disponibles en esta sucursal. Consulta al negocio.';$('customer-appointment-time').innerHTML='<option value="">Sin horas disponibles</option>';$('next-appointment-date').classList.add('hidden');return}setAppointmentVisibility(true);$('customer-appointment-service').innerHTML=services.map(s=>`<option value="${s.id}">${ES.escape(s.name)} · duración aproximada: ${s.duration_minutes} minutos${s.price===null?'':' · $'+Number(s.price).toLocaleString('es-CO')}</option>`).join('');await loadAppointmentDates()}catch(e){setAppointmentVisibility(false)}
}
let customerMonth=null;
function renderCustomerDates(data){
  const month=data.month,[year,number]=month.split('-').map(Number);
  const first=(new Date(Date.UTC(year,number-1,1)).getUTCDay()+6)%7;
  const count=new Date(Date.UTC(year,number,0)).getUTCDate();
  $('customer-calendar-month').textContent=new Intl.DateTimeFormat('es-CO',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(year,number-1,1)));
  const selected=$('customer-appointment-date').value;
  const cells=Array.from({length:first},()=>'<span class="calendar-empty"></span>');
  for(let day=1;day<=count;day++){
    const date=`${month}-${String(day).padStart(2,'0')}`,available=data.days[date]||0;
    cells.push(`<button type="button" class="calendar-date ${selected===date?'selected':''}" data-book-date="${date}" ${available?'':'disabled'}><b>${day}</b>${available?`<small>${available} cupo${available===1?'':'s'}</small>`:''}</button>`)
  }
  $('customer-calendar-days').innerHTML='<div class="calendar-weekdays">'+['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(x=>`<b>${x}</b>`).join('')+'</div><div class="calendar-grid">'+cells.join('')+'</div>';
  if(!data.days[selected]){$('customer-appointment-date').value='';$('customer-appointment-time').innerHTML='<option value="">Escoge una fecha primero</option>'}
  const chosen=$('customer-appointment-date').value;
  $('customer-chosen-date').textContent=chosen?`Fecha seleccionada: ${new Intl.DateTimeFormat('es-CO',{dateStyle:'full',timeZone:'UTC'}).format(new Date(chosen+'T12:00:00Z'))}`:'Selecciona un día disponible';
  $('customer-calendar-prev').disabled=month<=ES.dayKey(new Date(),data.timezone).slice(0,7);
  $('customer-calendar-next').disabled=month>=ES.dayKey(new Date(Date.now()+180*86400000),data.timezone).slice(0,7);
  if(!Object.keys(data.days).length)$('appointment-availability').textContent='Este mes no tiene citas disponibles. Revisa el mes siguiente.';
}
async function loadAppointmentDates(){
  const branch=+$('customer-appointment-branch').value,service=+$('customer-appointment-service').value;
  if(!branch||!service)return;
  customerMonth??=ES.dayKey(new Date(),customerTimeZone).slice(0,7);
  const month=customerMonth;
  $('customer-calendar-days').textContent='Buscando fechas disponibles…';
  try{const data=await api(`/api/public/${slug}/appointment-calendar?branch_id=${branch}&service_id=${service}&month=${month}`);
    if(branch!==+$('customer-appointment-branch').value||service!==+$('customer-appointment-service').value||month!==customerMonth)return;
    customerTimeZone=data.timezone;renderCustomerDates(data);
    if($('customer-appointment-date').value)await loadAppointmentAvailability();
  }catch(e){$('customer-calendar-days').textContent=e.message;showToast(e.message,'error')}
}
$('customer-calendar-days').onclick=event=>{const button=event.target.closest('[data-book-date]');if(!button||button.disabled)return;$('customer-appointment-date').value=button.dataset.bookDate;$('customer-chosen-date').textContent=`Fecha seleccionada: ${new Intl.DateTimeFormat('es-CO',{dateStyle:'full',timeZone:'UTC'}).format(new Date(button.dataset.bookDate+'T12:00:00Z'))}`;document.querySelectorAll('[data-book-date]').forEach(item=>item.classList.toggle('selected',item===button));loadAppointmentAvailability()};
function moveCustomerMonth(offset){const [year,number]=(customerMonth||ES.dayKey(new Date(),customerTimeZone).slice(0,7)).split('-').map(Number);const next=new Date(Date.UTC(year,number-1+offset,1));customerMonth=`${next.getUTCFullYear()}-${String(next.getUTCMonth()+1).padStart(2,'0')}`;$('customer-appointment-date').value='';$('customer-appointment-time').innerHTML='<option value="">Escoge una fecha primero</option>';loadAppointmentDates()}
$('customer-calendar-prev').onclick=()=>moveCustomerMonth(-1);
$('customer-calendar-next').onclick=()=>moveCustomerMonth(1);
async function loadAppointmentAvailability(){
  const date=$('customer-appointment-date').value,branch=+$('customer-appointment-branch').value,service=+$('customer-appointment-service').value;
  const select=$('customer-appointment-time');select.innerHTML='<option value="">Selecciona una fecha y servicio</option>';$('next-appointment-date').classList.add('hidden');
  if(!date||!branch||!service)return;
  try{const data=await api(`/api/public/${slug}/appointment-availability?branch_id=${branch}&service_id=${service}&date=${encodeURIComponent(date)}`);
    if(date!==$('customer-appointment-date').value||branch!==+$('customer-appointment-branch').value||service!==+$('customer-appointment-service').value)return;
    customerTimeZone=data.timezone;const available=data.slots.filter(x=>x.available).length;
    select.innerHTML='<option value="">Selecciona una hora disponible</option>'+data.slots.filter(x=>x.available).map(x=>`<option value="${x.starts_at}">${ES.clock(x.time)}</option>`).join('');
    const next=$('next-appointment-date');next.classList.toggle('hidden',available>0||!data.next_available_date);next.dataset.date=data.next_available_date||'';
    if(!available){$('appointment-availability').textContent=data.next_available_date?`No quedan citas disponibles el ${date}. El próximo día con cupos es ${data.next_available_date}.`:`No quedan citas disponibles el ${date}. Prueba con otra fecha.`;showToast('No hay más citas ese día. Elige el próximo día disponible.')}else $('appointment-availability').textContent=`${available} hora(s) disponible(s). Horario local del negocio. Elige la hora que prefieras.`;
  }catch(e){select.innerHTML='<option value="">Sin horarios disponibles</option>';$('appointment-availability').textContent=e.message;showToast(e.message,'error')}
}
async function loadMyAppointments(){
  try{const rows=await api('/api/public/me/appointments');$('customer-appointments').innerHTML=rows.length?'<h3>Mis citas</h3>'+rows.map(x=>{
    const active=['scheduled','confirmed'].includes(x.status)&&new Date(x.starts_at)>new Date();
    const delayed=x.delay_minutes?`<p class="delay-warning">Demora aproximada: ${x.delay_minutes} minutos. Fin estimado: ${ES.appointmentTime(x.estimated_end_at,x.tenant_timezone)}.</p>`:'';
    const cancel=x.status==='cancelled'&&x.cancellation_reason?`<p>Motivo de cancelación: ${ES.escape(x.cancellation_reason)}</p>`:'';
    return `<div class="history-item"><p><b>${ES.escape(x.service_name)}</b> · ${ES.appointmentStates[x.status]||ES.escape(x.status)}</p><p>${ES.escape(x.branch_name)}${x.city?' · '+ES.escape(x.city):''}</p><p>Duración aproximada: ${x.duration_minutes} minutos</p><p class="history-date">${ES.dateTime(x.starts_at,x.tenant_timezone)}</p>${delayed}${cancel}${active?`<details class="cancel-appointment"><summary>Cancelar esta cita</summary><form data-cancel-id="${x.id}"><label>Cuéntanos el motivo<textarea name="reason" rows="2" minlength="5" maxlength="500" required placeholder="Ejemplo: no podré asistir ese día"></textarea></label><button type="submit" class="secondary full">Confirmar cancelación</button></form></details>`:''}</div>`
  }).join(''):''}catch(e){$('customer-appointments').textContent='No fue posible consultar tus citas.'}
}
$('customer-appointments').addEventListener('submit',async event=>{
  const form=event.target.closest('form[data-cancel-id]');if(!form)return;
  event.preventDefault();const button=form.querySelector('button');button.disabled=true;
  try{await api(`/api/public/me/appointments/${form.dataset.cancelId}/cancel`,{method:'POST',body:JSON.stringify({reason:form.elements.reason.value.trim()})});showToast('Tu cita quedó cancelada. El horario volvió a estar disponible.','success');await Promise.all([loadMyAppointments(),loadAppointmentDates()])}
  catch(e){showToast(e.message,'error');button.disabled=false}
});
async function loadAppointmentModule(){
  if(!token||!customerModuleEnabled('appointments')){setAppointmentVisibility(false);return}
  try{const [profile,locations]=await Promise.all([api('/api/public/me/cards'),fetch(`/api/public/${slug}/branches`).then(r=>r.json())]);if(!locations.length)return;$('customer-appointment-branch').innerHTML=locations.map(b=>`<option value="${b.id}">${b.name}${b.city?' · '+b.city:''}</option>`).join('');if(profile.customer.origin_branch_id&&locations.some(b=>b.id===profile.customer.origin_branch_id))$('customer-appointment-branch').value=profile.customer.origin_branch_id;
    await Promise.all([loadCustomerAppointmentServices(),loadMyAppointments()])}catch(e){}
}
$('customer-appointment-branch').onchange=()=>{$('customer-appointment-date').value='';loadCustomerAppointmentServices()};
$('customer-appointment-service').onchange=()=>{$('customer-appointment-date').value='';loadAppointmentDates()};

$('next-appointment-date').onclick=async()=>{const next=$('next-appointment-date').dataset.date;if(next){customerMonth=next.slice(0,7);$('customer-appointment-date').value=next;await loadAppointmentDates();await loadAppointmentAvailability()}};
$('customer-appointment-form').onsubmit=async e=>{e.preventDefault();if(!$('customer-appointment-date').value||!$('customer-appointment-time').value){showToast('Escoge primero una fecha y un horario disponibles.','error');return}try{const created=await api('/api/public/me/appointments',{method:'POST',body:JSON.stringify({branch_id:+$('customer-appointment-branch').value,service_id:+$('customer-appointment-service').value,starts_at:$('customer-appointment-time').value,notes:$('customer-appointment-notes').value||null})});$('customer-appointment-message').textContent=`Cita agendada para ${ES.dateTime(created.starts_at,customerTimeZone)}.`;showToast('Cita agendada correctamente.','success');$('customer-appointment-notes').value='';await Promise.all([loadAppointmentDates(),loadAppointmentAvailability(),loadMyAppointments()])}catch(x){$('customer-appointment-message').textContent=x.message;showToast(x.message,'error');await loadAppointmentDates();await loadAppointmentAvailability()}};
let lastCustomerNotice=null,customerNoticeBusy=false;
async function pollCustomerNotices(){if(!token||!customerModuleEnabled('notifications')||customerNoticeBusy||document.hidden)return;customerNoticeBusy=true;try{const cursor=lastCustomerNotice===null?'':`?after_id=${lastCustomerNotice}`;const data=await api('/api/public/me/notifications'+cursor);lastCustomerNotice=data.last_id;data.items.forEach(x=>showToast(x.title+': '+x.message,'success',x.image_url||''))}catch(e){}finally{customerNoticeBusy=false}}
setInterval(pollCustomerNotices,3000);setTimeout(pollCustomerNotices,500);
setTimeout(loadAppointmentModule,450);
const rouletteRoot=document.querySelector('main.mobile-shell');if(rouletteRoot&&!document.getElementById('customer-roulette'))rouletteRoot.insertAdjacentHTML('beforeend','<section id="customer-roulette" class="hero-card hidden"><p class="eyebrow">MÓDULO INDEPENDIENTE · RULETA DE SUERTE</p><h2>🎡 Ruleta de suerte</h2><p class="muted">Gira y descubre tu premio.</p><div id="customer-roulette-list"></div></section>');applyCustomerModuleVisibility(customerModules);
async function loadCustomerRoulette(){const box=$('customer-roulette'),list=$('customer-roulette-list');if(!customerModuleEnabled('roulette')){box?.classList.add('hidden');if(list)list.replaceChildren();return}try{const rows=await api('/api/public/me/roulette');if(!box||!list)return;box.classList.toggle('hidden',!rows.length);list.innerHTML=rows.map(r=>`<div class="loyalty-card roulette-game-card"><h3>${r.name}</h3><p>Prueba tu suerte y descubre si ganas un premio.</p><button type="button" class="roulette-play-button" onclick="openCustomerRoulette(${r.id})">JUGAR</button><div id="roulette-game-${r.id}" class="roulette-game hidden"><div class="customer-wheel-slot" id="customer-wheel-${r.id}"></div><button type="button" onclick="customerSpin(${r.id})">GIRAR</button><p id="roulette-result-${r.id}" class="roulette-result"></p></div></div>`).join('');rows.forEach(r=>{const slot=$('customer-wheel-'+r.id);if(slot)slot.appendChild(publicWheel054(r.prizes))})}catch(e){}}
window.openCustomerRoulette=id=>{document.getElementById('roulette-game-'+id)?.classList.remove('hidden');document.querySelector('.roulette-play-button[onclick="openCustomerRoulette('+id+')"]')?.classList.add('hidden')};
function rouletteSound(win){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.type=win?'sine':'sawtooth';o.frequency.value=win?660:150;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.18,c.currentTime+.05);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+(win?5:.8));o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+(win?5:.8))}
window.customerSpin=async id=>{const wheel=document.querySelector('#customer-wheel-'+id+' .negrosky-wheel'),result=document.getElementById('roulette-result-'+id);if(wheel){wheel.style.transition='transform 4s cubic-bezier(.12,.75,.18,1)';wheel.style.transform='rotate(1440deg)'}try{const r=await api('/api/public/me/roulette/'+id+'/spin',{method:'POST'});setTimeout(()=>{const win=!/intenta|pierde|perder/i.test(r.prize);result.textContent=win?'🎉 ¡Ganaste: '+r.prize+'!':'😔 No ganaste esta vez: '+r.prize;result.className='roulette-result '+(win?'win':'lose');rouletteSound(win)},4000)}catch(e){showToast(e.message,'error')}};
loadCustomerRoulette();
setTimeout(()=>{if(token){loadCustomerRoulette();loadCustomerRaffles()}},3000);
function publicWheel054(prizes){const stage=document.createElement('div');stage.className='wheel-stage';const el=document.createElement('div');el.className='negrosky-wheel';const pointer=document.createElement('span');pointer.className='wheel-pointer';pointer.textContent='▼';const colors=['#8b5cf6','#ec4899','#06b6d4','#f59e0b','#10b981','#ef4444'];el.style.background='conic-gradient('+prizes.map((_,i)=>colors[i%colors.length]+' '+(i*100/prizes.length)+'% '+((i+1)*100/prizes.length)+'%').join(',')+')';el.innerHTML=prizes.map((p,i)=>'<span class="wheel-label" style="transform:rotate('+((i+.5)*360/prizes.length)+'deg) translateY(-72px) rotate('+(-((i+.5)*360/prizes.length))+'deg)">'+p+'</span>').join('');stage.append(pointer,el);return stage}
async function loadCustomerRaffles(){if(!token||!customerModuleEnabled('raffles'))return;try{const rows=await api('/api/public/me/raffles'),host=$('rewards');if(!host)return;let box=$('customer-raffles');if(!box){box=document.createElement('section');box.id='customer-raffles';box.className='hero-card';host.after(box)}box.innerHTML=rows.map(r=>`<div class="raffle-card"><p class="eyebrow">🎟️ RIFA</p><h2>${ES.escape(r.name)}</h2><p>${ES.escape(r.description||'Participa en el sorteo.')}</p><p><b>${r.tickets_per_purchase||1}</b> boleta(s) por compra · ${r.ticket_count?'Disponibles: '+r.tickets_available:'Boletas ilimitadas'}</p><p>Mis boletas: <b>${r.my_tickets}</b>${r.customer_ticket_limit?' · Límite: '+r.customer_ticket_limit:''}</p><button type="button" onclick="participateCustomerRaffle(${r.id})">Participar</button></div>`).join('');box.classList.toggle('hidden',!rows.length)}catch(e){}}
window.participateCustomerRaffle=async id=>{try{const r=await api('/api/public/me/raffles/'+id+'/participate',{method:'POST'});showToast(r.message,'success');await loadCustomerRaffles()}catch(e){showToast(e.message,'error')}};

// Public modules are resolved from the page URL, never from a stale customer session.
async function loadCustomerRoulette(){const box=$('customer-roulette'),list=$('customer-roulette-list');if(!customerModuleEnabled('roulette')){box?.classList.add('hidden');return}try{const response=await fetch(`/api/public/${slug}/roulette`,{cache:'no-store'});const rows=response.ok?await response.json():[];if(!box||!list)return;box.classList.toggle('hidden',!rows.length);list.innerHTML=rows.map(r=>`<div class="loyalty-card roulette-game-card"><h3>${r.name}</h3><p>Prueba tu suerte y descubre si ganas un premio.</p><button type="button" class="roulette-play-button" onclick="openCustomerRoulette(${r.id})">JUGAR</button><div id="roulette-game-${r.id}" class="roulette-game hidden"><div class="customer-wheel-slot" id="customer-wheel-${r.id}"></div><button type="button" onclick="customerSpin(${r.id})">GIRAR</button><p id="roulette-result-${r.id}" class="roulette-result"></p></div></div>`).join('');rows.forEach(r=>{const slot=$('customer-wheel-'+r.id);if(slot)slot.appendChild(publicWheel054(r.prizes))})}catch(e){box?.classList.add('hidden')}}
async function loadCustomerRaffles(){if(!customerModuleEnabled('raffles'))return;try{const response=await fetch(`/api/public/${slug}/raffles`,{cache:'no-store'});const rows=response.ok?await response.json():[],host=$('rewards');if(!host)return;let box=$('customer-raffles');if(!box){box=document.createElement('section');box.id='customer-raffles';box.className='hero-card';host.after(box)}box.innerHTML=rows.map(r=>`<div class="raffle-card"><p class="eyebrow">🎟️ RIFA</p><h2>${ES.escape(r.name)}</h2><p>${ES.escape(r.description||'Participa en el sorteo.')}</p><p><b>${r.tickets_per_purchase||1}</b> boleta(s) por compra · ${r.ticket_count?'Disponibles: '+r.tickets_available:'Boletas ilimitadas'}</p><button type="button" onclick="participateCustomerRaffle(${r.id})">Participar</button></div>`).join('');box.classList.toggle('hidden',!rows.length)}catch(e){}}

// Corrección final: una sola implementación estable y el slug se normaliza para /negocio/.
const customerPathSlug=location.pathname.replace(/\/+$/,'').split('/').pop();
renderCustomerSchedule=function(b){const home=$('customer-home');if(!home)return;let box=$('customer-schedule');if(!box){box=document.createElement('section');box.id='customer-schedule';box.className='schedule-panel hidden';box.innerHTML='<button id="customer-schedule-toggle" type="button" class="schedule-toggle" aria-expanded="false">🕒 Horarios <span>＋</span></button><div id="customer-schedule-content" class="schedule-content hidden"></div>';home.insertBefore(box,$('customer-profile'));$('customer-schedule-toggle').onclick=()=>{const c=$('customer-schedule-content'),closed=c.classList.toggle('hidden');$('customer-schedule-toggle').setAttribute('aria-expanded',String(!closed));$('customer-schedule-toggle').querySelector('span').textContent=closed?'＋':'−'}}const rows=b.business_hours||[];const enabled=Boolean(b.show_business_hours&&rows.length);box.classList.toggle('hidden',!enabled);if(!enabled)return;const c=$('customer-schedule-content');c.innerHTML='<h3>Horario de atención</h3>'+rows.map(row=>`<div class="customer-hour-row"><span>${publicDayNames[row.weekday]}</span><b>${row.enabled?formatBusinessHour(row.opens_at)+' – '+formatBusinessHour(row.closes_at):'Cerrado'}</b></div>`).join('')};
loadCustomerRaffles=async function(){if(!customerModuleEnabled('raffles'))return;try{const response=await fetch(`/api/public/${encodeURIComponent(customerPathSlug)}/raffles`,{cache:'no-store'});if(!response.ok)throw Error('HTTP '+response.status);const rows=await response.json(),host=$('rewards');if(!host)return;let box=$('customer-raffles');if(!box){box=document.createElement('section');box.id='customer-raffles';box.className='hero-card';host.after(box)}box.innerHTML=rows.map(r=>`<div class="raffle-card">${r.image_url?`<img class="raffle-prize-image" src="${ES.escape(r.image_url)}" alt="Premio">`:''}<p class="eyebrow">🎟️ RIFA</p><h2>${ES.escape(r.name)}</h2><p>${ES.escape(r.description||'Participa en el sorteo.')}</p><p><b>${r.tickets_per_purchase||1}</b> boleta(s) por compra · ${r.ticket_count?'Disponibles: '+r.tickets_available:'Boletas ilimitadas'}</p><button type="button" onclick="participateCustomerRaffle(${r.id})">Participar</button></div>`).join('');box.classList.toggle('hidden',!rows.length)}catch(e){console.warn('Rifas:',e.message)}};
const _loadCustomerRafflesStable=loadCustomerRaffles;
loadCustomerRaffles=async function(){if(window.__raffleInteractionActive||document.querySelector('#customer-raffles .raffle-operation-code, #customer-raffles .raffle-number-picker, #customer-raffles [data-buying-again="1"]'))return;return _loadCustomerRafflesStable()};
$('public-hours')?.classList.add('hidden');
// El acceso superior es el único botón de Horarios; el panel inferior solo contiene la información.
function bindSingleScheduleButton(){const quick=document.querySelector('[data-scroll-target="customer-schedule"]');if(!quick)return;quick.onclick=()=>{const box=$('customer-schedule'),content=$('customer-schedule-content');if(!box||!content)return;const closed=content.classList.toggle('hidden');box.classList.toggle('hidden',closed);if(!closed)box.scrollIntoView({behavior:'smooth',block:'start'})};const extra=$('customer-schedule-toggle');if(extra)extra.remove()}
bindScheduleQuickButton=bindSingleScheduleButton;
setTimeout(bindSingleScheduleButton,0);
// Publicidad global del Administrador General: aparece una vez por campaña y negocio.
async function loadCustomerPlatformAds(){if(!token)return;try{const rows=await fetch(`/api/public/${encodeURIComponent(slug)}/platform-ads`,{cache:'no-store'}).then(r=>r.ok?r.json():[]);const item=rows.find(x=>!sessionStorage.getItem(`negrosky_platform_ad_${slug}_${x.id}`));if(!item)return;sessionStorage.setItem(`negrosky_platform_ad_${slug}_${item.id}`,'1');const seconds=Math.max(1,Math.min(60,Number(item.ad_seconds)||5));const overlay=document.createElement('div');overlay.className='collaboration-overlay platform-ad-overlay';overlay.innerHTML=`<article class="collaboration-ad platform-ad"><button type="button" class="collaboration-close" aria-label="Cerrar">×</button><p class="eyebrow">PUBLICIDAD NEGROSKY</p><h2>${ES.escape(item.title||'Promoción especial')}</h2>${item.image_url?`<img src="${ES.escape(item.image_url)}" alt="Publicidad">`:''}<p>${ES.escape(item.message||'')}</p><small>Esta publicidad se cerrará en ${seconds} segundos.</small></article>`;document.body.appendChild(overlay);const close=()=>overlay.remove();overlay.querySelector('.collaboration-close').onclick=close;setTimeout(close,seconds*1000)}catch(e){}}
const showHomeBeforePlatformAds=showHome;showHome=async function(){const result=await showHomeBeforePlatformAds();if(token)await loadCustomerPlatformAds();return result};
// Varias campañas se muestran en cola, nunca como ventanas superpuestas.
async function loadCustomerPlatformAds(){if(!token)return;try{const rows=await fetch(`/api/public/${encodeURIComponent(slug)}/platform-ads`,{cache:'no-store'}).then(r=>r.ok?r.json():[]);for(const item of rows){if(sessionStorage.getItem(`negrosky_platform_ad_${slug}_${item.id}`))continue;sessionStorage.setItem(`negrosky_platform_ad_${slug}_${item.id}`,'1');const seconds=Math.max(1,Math.min(60,Number(item.ad_seconds)||5));await new Promise(resolve=>{const overlay=document.createElement('div');overlay.className='collaboration-overlay platform-ad-overlay';overlay.innerHTML=`<article class="collaboration-ad platform-ad"><button type="button" class="collaboration-close" aria-label="Cerrar">×</button><p class="eyebrow">PUBLICIDAD NEGROSKY</p><h2>${ES.escape(item.title||'Promoción especial')}</h2>${item.image_url?`<img src="${ES.escape(item.image_url)}" alt="Publicidad">`:''}<p>${ES.escape(item.message||'')}</p><small>Esta publicidad se cerrará en ${seconds} segundos.</small></article>`;document.body.appendChild(overlay);let closed=false;const close=()=>{if(closed)return;closed=true;overlay.remove();resolve()};overlay.querySelector('.collaboration-close').onclick=close;setTimeout(close,seconds*1000)})}}catch(e){}}
// Captura de cumpleaños en el primer registro del cliente.
const birthdayIdentifyForm=$('identify-form');if(birthdayIdentifyForm)birthdayIdentifyForm.onsubmit=async e=>{e.preventDefault();const wantsWhatsApp=$('consent').checked,birthdayConsent=$('birthday-consent')?.checked||false,name=$('customer-name').value.trim(),phone=$('customer-phone').value.replace(/\D/g,''),birthDate=$('customer-birth-date')?.value||null;let whatsappWindow=null;if(wantsWhatsApp&&publicBranding?.whatsapp_number)whatsappWindow=window.open('about:blank','_blank');try{const r=await api(`/api/public/${slug}/identify`,{method:'POST',body:JSON.stringify({name,phone,marketing_consent:wantsWhatsApp,birth_date:birthDate,birthday_consent:birthdayConsent,branch_id:+($('customer-branch')?.value||0)||null})});token=r.access_token;localStorage.setItem(`customer_${slug}`,token);localStorage.setItem('negrosky_global_customer',JSON.stringify({name,phone}));document.documentElement.classList.add('customer-session');$('identify-box')?.classList.add('hidden');$('customer-home')?.classList.add('hidden');await loadPublicBranding();if(wantsWhatsApp&&!openWhatsAppOptIn(name,phone,whatsappWindow)&&whatsappWindow)whatsappWindow.close();await showHome()}catch(x){if(whatsappWindow)whatsappWindow.close();$('customer-error').textContent=x.message;showToast(x.message,'error')}};
