const ES=window.NegroskyES;const $=id=>document.getElementById(id);
let token=localStorage.getItem('worker_token');
let preview=null;
let workerModules={loyalty:true,appointments:true,time_sales:true,notifications:true,public_page:true,raffles:true,roulette:true};
let workerPermissionBusy=false;
const workerAudio=new Audio('/static/success.wav?v=15');
workerAudio.preload='auto';workerAudio.setAttribute('playsinline','');
let workerSoundUnlocked=false;
const queryCode=new URLSearchParams(location.search).get('code');
const queryBusiness=new URLSearchParams(location.search).get('business');
document.querySelector('main.mobile-shell > section:first-child')?.classList.add('legacy-worker-header');
function ensureWorkerLoyaltyModule(){const home=$('worker-home'),anchor=$('operation-code')?.closest('label');if(!home||!anchor||home.querySelector('[data-worker-module="loyalty"]'))return;const wrapper=document.createElement('section');wrapper.id='worker-loyalty-module';wrapper.className='worker-loyalty-module';wrapper.dataset.workerModule='loyalty';home.insertBefore(wrapper,anchor);let node=anchor;while(node&&!(node.nodeType===1&&node.classList.contains('worker-appointments'))){const next=node.nextSibling;wrapper.appendChild(node);node=next}}
ensureWorkerLoyaltyModule();
async function loadLoginBranding(){
  if(!queryBusiness)return;
  try{
    const r=await fetch(`/api/public/${encodeURIComponent(queryBusiness)}/branding`);
    if(!r.ok)return;
    const b=await r.json();
    const box=$('worker-login'); if(!box)return;
    let identity=document.createElement('div'); identity.className='worker-login-brand';
    identity.innerHTML=b.logo_url?`<img src="${b.logo_url}?v=${Date.now()}" alt="Logo del negocio">`:'<div class="brand-mark">N</div>';
    const title=document.createElement('h2'); title.textContent=b.display_name||b.business_name||queryBusiness;
    identity.appendChild(title); box.prepend(identity);
    if(b.primary_color)document.documentElement.style.setProperty('--purple',b.primary_color);
    if(b.secondary_color)document.documentElement.style.setProperty('--purple2',b.secondary_color);
  }catch(e){}
}
loadLoginBranding();
function cleanCode(value){
  const raw=String(value||'').trim();
  try{const url=new URL(raw,location.origin);return url.searchParams.get('code')||raw.replace(/\D/g,'').slice(-6)}catch(e){return raw.replace(/\D/g,'').slice(-6)}
}
function armWorkerSound(){if(workerSoundUnlocked)return;try{workerAudio.volume=.01;workerAudio.currentTime=0;const play=workerAudio.play();if(play)play.then(()=>{setTimeout(()=>{workerAudio.pause();workerAudio.currentTime=0;workerAudio.volume=1;workerSoundUnlocked=true},80)}).catch(()=>{})}catch(e){}}
function workerSuccessSound(){workerAudio.volume=1;workerAudio.currentTime=0;workerAudio.play().catch(()=>{})}
async function api(path,o={}){const r=await fetch(path,{...o,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`}});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(Array.isArray(b.detail)?'Revisa los datos e inténtalo de nuevo.':b.detail||'No fue posible completar la operación');return b}
const workerIdentityPath=()=>queryBusiness?`/api/me?business=${encodeURIComponent(queryBusiness)}`:'/api/me';
function applyWorkerFeatureVisibility(enabled){if(Array.isArray(enabled)){const allowed=new Set(enabled);workerModules=Object.fromEntries(Object.keys(workerModules).map(key=>[key,allowed.has(key)]))}document.querySelectorAll('[data-worker-module]').forEach(el=>el.classList.toggle('hidden',workerModules[el.dataset.workerModule]===false));}
function workerModuleEnabled(key){return workerModules[key]!==false}
async function refreshWorkerPermissions(){if(!token||workerPermissionBusy)return;workerPermissionBusy=true;try{const before={...workerModules};const me=await api(workerIdentityPath());applyWorkerFeatureVisibility(me.enabled_modules);if(workerModuleEnabled('appointments')&&!before.appointments)loadWorkerAppointments();if(workerModuleEnabled('time_sales')&&!before.time_sales)loadWorkerTime()}catch(e){}finally{workerPermissionBusy=false}}
async function home(){const me=await api(workerIdentityPath());applyWorkerFeatureVisibility(me.enabled_modules);$('worker-login').classList.add('hidden');$('worker-home').classList.remove('hidden');$('worker-name').textContent=`${me.name} · Trabajador`;if(workerModuleEnabled('appointments'))loadWorkerAppointments();if(workerModuleEnabled('time_sales'))loadWorkerTime();if(queryCode&&(workerModuleEnabled('loyalty')||workerModuleEnabled('raffles'))){$('operation-code').value=cleanCode(queryCode);await loadPreview()}}
$('worker-form').onsubmit=async e=>{e.preventDefault();armWorkerSound();try{const currentPassword=$('worker-password').value;const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identifier:$('worker-email').value,password:currentPassword})});const b=await r.json();if(!r.ok)throw Error(b.detail);token=b.access_token;localStorage.setItem('worker_token',token);if(b.user.force_password_change){const newPassword=prompt('Por seguridad debes cambiar la contraseña temporal. Escribe una nueva contraseña de mínimo 8 caracteres:');if(!newPassword){localStorage.removeItem('worker_token');token=null;throw Error('Debes cambiar la contraseña temporal para continuar.')}await api('/api/auth/change-password',{method:'POST',body:JSON.stringify({current_password:currentPassword,new_password:newPassword})})}await home()}catch(x){showToast(x.message,'error')}};
async function loadPreview(){armWorkerSound();const code=cleanCode($('operation-code').value);$('operation-code').value=code;if(code.length!==6){$('worker-result').textContent='Escribe o escanea un código de seis números.';return}const result=$('worker-result');result.className='status-panel pending';result.textContent='Consultando datos del cliente…';try{try{preview=await api(`/api/operations/preview/${code}`)}catch(first){preview=await api(`/api/raffle-operations/preview/${code}`)}const isPurchase=preview.operation==='purchase',isRaffle=preview.operation==='raffle';$('operation-preview').classList.remove('hidden');$('operation-preview').innerHTML=`<p class="eyebrow">VERIFICA ANTES DE AUTORIZAR</p><h2>${preview.customer_name}</h2><p>Celular: <b>${preview.customer_phone}</b></p><p>${isRaffle?`Rifa: <b>${preview.raffle_name}</b><br>Boletas: <b>${(preview.ticket_numbers||[]).join(', ')}</b>`:isPurchase?`Campaña: <b>${preview.program_name}</b><br>Registrar una compra`:`Entregar ${preview.quantity} premio(s): ${preview.reward_name}`}</p><button class="full authorize-button" onclick="authorizePreview()">${isRaffle?'Permitir boletas':`Autorizar ${isPurchase?'compra':'entrega'}`}</button>${isRaffle?'<button class="secondary full" onclick="rejectRaffleOperation()">Rechazar participación</button>':''}<button class="secondary full" onclick="cancelPreview()">Cancelar</button>`;result.textContent='Confirma que los datos correspondan al cliente.'}catch(e){preview=null;$('operation-preview').classList.add('hidden');result.className='status-panel error';result.textContent=e.message;showToast(e.message,'error')}}
async function authorizePreview(){if(!preview)return;const isRaffle=preview.operation==='raffle',type=preview.operation==='purchase'?'purchase':'reward';const result=$('worker-result');result.className='status-panel pending';result.textContent='Autorizando operación…';try{const r=await api(isRaffle?'/api/raffle-operations/validate':`/api/operations/validate-${type}`,{method:'POST',body:JSON.stringify({code:preview.code})});result.className='status-panel success';result.textContent=isRaffle?`✓ Boletas permitidas: ${(r.ticket_numbers||[]).join(', ')}`:type==='purchase'?`✓ Compra validada para ${r.customer_name}. Progreso ${r.progress}/${r.target}`:`✓ ${r.count||1} premio(s) entregado(s) a ${r.customer_name}: ${r.name}`;$('operation-code').value='';$('operation-preview').classList.add('hidden');preview=null;history.replaceState({},'',location.pathname);workerSuccessSound();showToast('Operación validada correctamente.','success');if(navigator.vibrate)navigator.vibrate([150,80,150])}catch(e){result.className='status-panel error';result.textContent=e.message;showToast(e.message,'error')}}
async function rejectRaffleOperation(){if(!preview||preview.operation!=='raffle')return;if(!confirm('¿Rechazar esta participación y liberar sus boletas?'))return;try{await api('/api/raffle-operations/reject',{method:'POST',body:JSON.stringify({code:preview.code})});$('worker-result').className='status-panel success';$('worker-result').textContent='Participación rechazada y boletas liberadas.';cancelPreview()}catch(e){showToast(e.message,'error')}}
function cancelPreview(){preview=null;$('operation-preview').classList.add('hidden');$('worker-result').textContent='Operación cancelada. No se registró ningún cambio.'}
$('preview-button').onclick=loadPreview;
$('operation-code').oninput=e=>{e.target.value=cleanCode(e.target.value)};
$('operation-code').insertAdjacentHTML('afterend',`<div class="numeric-keypad">${[1,2,3,4,5,6,7,8,9].map(n=>`<button type="button" data-digit="${n}">${n}</button>`).join('')}<button type="button" class="clear" data-clear>Limpiar</button><button type="button" data-digit="0">0</button><button type="button" class="clear" data-back>⌫</button></div>`);
document.querySelector('.numeric-keypad').onclick=e=>{const button=e.target.closest('button');if(!button)return;armWorkerSound();if(button.dataset.clear!==undefined)$('operation-code').value='';else if(button.dataset.back!==undefined)$('operation-code').value=$('operation-code').value.slice(0,-1);else if($('operation-code').value.length<6)$('operation-code').value+=button.dataset.digit||''};
$('scan-button').onclick=async()=>{armWorkerSound();if(!('BarcodeDetector'in window)){alert('Este navegador no permite escaneo automático. Usa la cámara normal del celular: el QR abrirá esta página directamente.');return}try{const v=$('camera');v.classList.remove('hidden');v.srcObject=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});await v.play();const d=new BarcodeDetector({formats:['qr_code']});const loop=async()=>{const codes=await d.detect(v);if(codes.length){$('operation-code').value=cleanCode(codes[0].rawValue);v.srcObject.getTracks().forEach(t=>t.stop());v.classList.add('hidden');await loadPreview()}else requestAnimationFrame(loop)};loop()}catch(e){$('worker-result').className='status-panel error';$('worker-result').textContent='No fue posible abrir la cámara. Revisa el permiso del navegador.'}};
if(queryCode)$('pending-login-note').classList.remove('hidden');
$('worker-customer-form').onsubmit=async e=>{e.preventDefault();try{const r=await api('/api/customers/assisted',{method:'POST',body:JSON.stringify({phone:$('worker-customer-phone').value,name:$('worker-customer-name').value||null})});$('worker-customer-message').textContent=r.message;showToast(r.message,'success');e.target.reset()}catch(x){$('worker-customer-message').textContent=x.message;showToast(x.message,'error')}};
if(token)home().catch(e=>{localStorage.removeItem('worker_token');token=null;const note=$('pending-login-note');note.textContent=e.message;note.classList.remove('hidden');showToast(e.message,'error')});

// Confirmación visible y sonora para rifas: el trabajador ve cliente, vendedor, hora y boletas.
window.authorizePreview=async function(){if(!preview)return;const isRaffle=preview.operation==='raffle',type=preview.operation==='purchase'?'purchase':'reward',result=$('worker-result');result.className='status-panel pending';result.textContent='Autorizando operación…';try{const r=await api(isRaffle?'/api/raffle-operations/validate':`/api/operations/validate-${type}`,{method:'POST',body:JSON.stringify({code:preview.code})});const when=r.validated_at?new Date(r.validated_at).toLocaleString('es-CO',{dateStyle:'short',timeStyle:'short'}):new Date().toLocaleString('es-CO',{dateStyle:'short',timeStyle:'short'});if(isRaffle){result.className='status-panel success';result.innerHTML=`<h3>✅ Participación verificada</h3><p>Cliente: <b>${r.customer_name||preview.customer_name}</b></p><p>Rifa: <b>${r.raffle_name||preview.raffle_name}</b></p><p>Boletas: <b>${(r.ticket_numbers||[]).join(', ')}</b></p><p>Hora: <b>${when}</b></p><p>Vendedor: <b>${r.seller_name||'Trabajador'}</b></p>`}else{result.className='status-panel success';result.textContent=type==='purchase'?`✓ Compra validada para ${r.customer_name}. Progreso ${r.progress}/${r.target}`:`✓ ${r.count||1} premio(s) entregado(s) a ${r.customer_name}: ${r.name}`}$('operation-code').value='';$('operation-preview').classList.add('hidden');preview=null;history.replaceState({},'',location.pathname);workerSuccessSound();showToast('Operación validada correctamente.','success');if(navigator.vibrate)navigator.vibrate([150,80,150])}catch(e){result.className='status-panel error';result.textContent=e.message;showToast(e.message,'error')}};

async function loadWorkerAppointments(){if(!token||!workerModuleEnabled('appointments'))return;try{const rows=await api('/api/worker/appointments');$('worker-appointments-list').innerHTML=rows.length?rows.map(x=>`<article class="worker-appointment"><b>${ES.dateTime(x.starts_at,x.tenant_timezone)}</b><p>${ES.escape(x.customer_name)} · ${ES.escape(x.service_name)}</p><p>Duración aproximada: ${x.duration_minutes} minutos${x.delay_minutes?` · Demora: ${x.delay_minutes} minutos`:''}</p>${ES.delayForm(x.id,x.delay_minutes||0)}</article>`).join(''):'<p class="muted">No hay citas activas hoy ni mañana.</p>'}catch(e){$('worker-appointments-list').textContent='No fue posible cargar las citas de la sucursal.'}}
$('worker-refresh-appointments').onclick=loadWorkerAppointments;
$('worker-appointments-list').addEventListener('submit',async event=>{const form=event.target.closest('.delay-form');if(!form)return;event.preventDefault();const button=form.querySelector('button');button.disabled=true;try{const response=await api(`/api/appointments/${form.dataset.delayId}/delay`,{method:'POST',body:JSON.stringify({delay_minutes:+form.elements.minutes.value,reason:form.elements.reason.value||null})});showToast(response.affected_count?`Demora registrada. ${response.affected_count} cita(s) podrían verse afectadas.`:'Demora registrada.','success');await loadWorkerAppointments()}catch(e){showToast(e.message,'error');button.disabled=false}});
async function loadWorkerTime(){if(!token||!workerModuleEnabled('time_sales'))return;try{const [services,sessions]=await Promise.all([api('/api/time-services'),api('/api/worker/time-sessions')]);const select=$('worker-time-service'),old=select.value;select.innerHTML='<option value="">Selecciona un servicio</option>'+services.filter(x=>x.status==='active').map(x=>`<option value="${x.id}">${ES.escape(x.name)} · ${x.duration_minutes} min · $${Number(x.price).toLocaleString('es-CO')}</option>`).join('');select.value=old;const now=Date.now();$('worker-time-sessions').innerHTML=sessions.length?sessions.map(x=>{const minutes=x.status==='open'?Math.max(1,Math.ceil((now-new Date(x.started_at))/60000)):x.minutes_used;return `<article class="worker-appointment"><b>${x.status==='open'?'🟢 En curso':'✓ Cerrada'} · ${ES.escape(x.service_name)}</b><p>${ES.escape(x.customer_name)} · ${minutes} minuto(s)</p>${x.status==='open'?`<button type="button" class="secondary" data-close-time="${x.id}">Cerrar sesión</button>`:`<p>Precio: $${Number(x.total_price||0).toLocaleString('es-CO')}</p>`}</article>`}).join(''):'<p class="muted">No hay sesiones por tiempo.</p>'}catch(e){$('worker-time-sessions').textContent='No se pudo cargar venta por tiempo.'}}
async function searchWorkerTimeCustomer(){const q=$('worker-time-search').value.trim();if(q.length<2){showToast('Escribe al menos dos caracteres.','error');return}try{const rows=await api('/api/worker/customers?q='+encodeURIComponent(q));$('worker-time-customer').innerHTML=rows.length?'<option value="">Selecciona el cliente</option>'+rows.map(x=>`<option value="${x.id}">${ES.escape(x.name)} · ${ES.escape(x.phone)}</option>`).join(''):'<option value="">No se encontraron clientes</option>'}catch(e){showToast(e.message,'error')}}
$('worker-time-search-button').onclick=searchWorkerTimeCustomer;$('worker-time-form').onsubmit=async e=>{e.preventDefault();try{const r=await api('/api/time-sessions',{method:'POST',body:JSON.stringify({branch_id:(await api('/api/me')).branch_id,service_id:+$('worker-time-service').value,customer_id:+$('worker-time-customer').value})});$('worker-time-message').textContent=`Sesión iniciada para ${r.customer_name}.`;showToast('Sesión iniciada correctamente.','success');await loadWorkerTime()}catch(e){$('worker-time-message').textContent=e.message;showToast(e.message,'error')}};$('worker-time-sessions').onclick=async e=>{const id=e.target.dataset.closeTime;if(!id)return;try{const r=await api(`/api/time-sessions/${id}/close`,{method:'POST',body:JSON.stringify({})});showToast(`Sesión cerrada: ${r.minutes_used} min.`,'success');await loadWorkerTime()}catch(x){showToast(x.message,'error')}};$('worker-refresh-time').onclick=loadWorkerTime;
setInterval(()=>{if(token&&!document.hidden){refreshWorkerPermissions();loadWorkerAppointments();loadWorkerTime()}},30000);
setInterval(()=>{if(token&&!document.hidden)refreshWorkerPermissions()},5000);

async function renderWorkerIdentity(){
  if(!token)return;
  try{
    const me=await api(workerIdentityPath());
    let card=$('worker-identity');
    if(!card){card=document.createElement('section');card.id='worker-identity';card.className='worker-identity hero-card';$('worker-home').prepend(card)}
    const title=me.display_name||me.tenant_name||'Negocio';
    card.innerHTML=`${me.has_logo?`<img class="worker-business-logo" src="/api/public/branding/${me.tenant_id}/logo?v=${Date.now()}" alt="Logo del negocio">`:'<div class="brand-mark">N</div>'}<p class="eyebrow worker-accent">PANEL DEL TRABAJADOR</p><h2>${ES.escape(title)}</h2><p class="worker-branch-label">📍 Sucursal: <b>${ES.escape(me.branch_name||'Sucursal general')}</b></p><p class="worker-action-label">Validar operación</p><p class="muted">Trabajador: ${ES.escape(me.name)}</p>`;
    if(me.primary_color)document.documentElement.style.setProperty('--purple',me.primary_color);
    if(me.secondary_color)document.documentElement.style.setProperty('--purple2',me.secondary_color);
  }catch(e){}
}
setTimeout(renderWorkerIdentity,350);
